#:schema node_modules/wrangler/config-schema.json
name = "14july"
main = "src/worker.jsx"
compatibility_date = "2024-07-24"
compatibility_flags = ["nodejs_compat"]

kv_namespaces = [
  { binding = "SUBLINK_KV", id = "dee9c8d4584d4eb3813d09c6cc76a18a" }
]

[assets]
directory = "./public"
